# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CTNJ Prototype
email: mzagaja@alum.wpi.edu
description: > # this means to ignore newlines until "baseurl:"
  This is a design prototype for CTNJ.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mzagaja.github.io/ctnj-prototype" # the base hostname & protocol for your site
twitter_username: mzagaja
github_username:  mzagaja

# Build settings
markdown: kramdown